## docker-compose to API-ToSQS whit GORM
version: '3.3'
services:
  go_tosqs_api:
    ports:
      - '9072:8000'
    image: 'tosqs_api:latest'
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - '.:/usr/src/app'    
