<<<<<<< HEAD
@echo off
set POSTGRES_HOST=localhost
set POSTGRES_PORT=5432
set POSTGRES_USER=postgres
set POSTGRES_PASSWORD=xxxxxxx
set POSTGRES_DATABASE=xxxxxxx
set API_TOKEN='api_token'
set API_PORT=9072
set FILENAME='domainlist.txt'
=======
@echo off
set POSTGRES_HOST=localhost
set POSTGRES_PORT=5432
set POSTGRES_USER=postgres
set POSTGRES_PASSWORD=xxxxxxx
set POSTGRES_DATABASE=xxxxxxx
set API_TOKEN='api_token'
set API_PORT=9072
set FILENAME='domainlist.txt'
>>>>>>> 8c5dc376e070a3ae8e7b635ff305a2728f05949e
