source ../db/.docker.env.sh
export POSTGRES_HOST="localhost"
export POSTGRES_PORT=myport
export POSTGRES_USER=myuser
export POSTGRES_PASSWORD=mypassw
export POSTGRES_DATABASE=mydb
export API_TOKEN='api_token'
export API_PORT=9072
export FILEIN='domain.json'
export API_PORT=9072
export QUEUE_NAME=xxxxxxx
export SQS_REGION=xx-xxxx-x
export URL_RESPONSE=http://localhost:8080
